
name: Compile and check

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

env:
  EXECUTABLES: "a.out"

jobs:
  compile_and_run_tests:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile program
        run: make; make fclean; make re

      # fail if executable is not found
      - name: Check executables
        run: |
          echo "## Executables" >> $GITHUB_STEP_SUMMARY
          for executable in $EXECUTABLES; do
            if [ ! -f $executable ]; then
              echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
              echo "Error: $executable not found" >> $GITHUB_STEP_SUMMARY
              echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
              exit 1
            fi
          done

      - name: Run tests and generate coverage reports
        run: |
            echo "## Unit Tests" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            make tests_run 2>> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            echo "## Coverage" >> $GITHUB_STEP_SUMMARY
            echo "### Lines" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            gcovr --txt --exclude tests/ --exclude src/main.c >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            echo "### Branches" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            gcovr --txt --exclude tests/ --exclude src/main.c --branches >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
